

export const questionData = {

    gettingToKnow: [
        "What did you dream of as a child?",
        "If you knew you couldn't fail what is one thing you would do?",
        "What is your least expressed emotion?",
        "What does a perfect day look like for you?",
        "What are you most afraid of?",
        "What's one thing you are trying to get better at right now?",
        "What do you struggle with the most?",
        "What's a belief you had that you completely changed your mind about?",
        "What do you look forward to, the most, each day?",
        "What's something about yourself that most people don't know?",
        "When do you feel most like yourself?",
        "What's a risk you've been wanting to take?",
        "What makes you feel alive?",
        "What does success mean to you?",
        "What's the best advice you've ever received?",
        "What's a small thing that brings you genuine joy?",
        "Who has had the biggest impact on who you are today?",
        "What's something you're proud of that you rarely talk about?",
        "What's a habit you've been meaning to start or break?",
        "If you could relive one year of your life, which would it be?",
        "What's the hardest lesson you've had to learn?",
        "What do you wish you spent more time doing?",
        "What's something that used to matter to you but doesn't anymore?",
        "When was the last time you did something for the first time?",
        "What's a compliment you've never forgotten?",
        "What does home feel like to you?",
        "What are you most grateful for right now?",
        "What's a moment that changed your perspective on life?",
        "What do you need more of in your life?",
        "What's something you've outgrown?",
        "What makes you trust someone?",
        "What's a question you wish people would ask you more often?",
        "What's the kindest thing someone has done for you?",
        "What are you currently overthinking?",
        "What does your inner critic sound like?",
    ],

    deep: [
        "Do you think people can fundamentally change, or do we just become more of who we already are?",
        "What makes a conversation actually meaningful to you?",
        "What do you think happens after we die?",
        "Do you believe we're alone in the universe?",
        "Is it more important to be liked or respected?",
        "What role does suffering play in growth?",
        "Do you think we have free will, or are we products of our circumstances?",
        "What's something you believe that most people would disagree with?",
        "What do you think is the purpose of discomfort in life?",
        "If you could know the exact date of your death, would you want to?",
        "What's a truth you've learned that you wish you'd known sooner?",
        "Do you think happiness is a choice or a circumstance?",
        "What's the difference between being alone and being lonely?",
        "Is it possible to be truly selfless, or is every action motivated by self-interest?",
        "What do you think we owe to strangers?",
        "Do you believe in second chances? What about third ones?",
        "What's more valuable: intelligence or wisdom?",
        "Is vulnerability a strength or a weakness?",
        "Do you think the universe has a purpose, or is it random?",
        "What do you think holds people back from being authentic?",
        "Is it better to have loved and lost or never to have loved at all?",
        "What makes someone truly brave?",
        "Do you think we're defined by our intentions or our actions?",
        "What's the relationship between pain and meaning?",
        "Is forgiveness more for the forgiver or the forgiven?",
        "What do you think people misunderstand most about human nature?",
        "How do you know when you're being honest with yourself?",
        "What's the difference between giving up and letting go?",
        "Do you think some people are meant to be in our lives temporarily?",
        "What does it mean to truly know someone?",
        "Is it possible to love someone without understanding them?",
        "What do you think we lose as we grow older?",
        "Do you believe everything happens for a reason?",
        "What makes a life meaningful?",
        "How do you balance being present with planning for the future?",
        "What's the hardest thing about being human?",
    ],

    creative: [
        "If you could master any skill instantly, what would it be and why?",
        "What's something you've created that you're proud of?",
        "If you could live in any fictional world, which would you choose?",
        "What would you do if you had unlimited resources for one year?",
        "If you could have dinner with anyone, dead or alive, who would it be and what would you ask?",
        "What would your autobiography be titled?",
        "If you could change one moment in history, what would it be?",
        "What's a problem you wish you could solve?",
        "If you wrote a book about your life, what would the current chapter be called?",
        "If your life had a theme song, what would it be?",
        "What would you build if you knew it would last 1000 years?",
        "If you could experience any moment in history firsthand, which would you choose?",
        "What would you do with an extra hour every day that no one else had?",
        "If you could design your dream home, what's the one must-have feature?",
        "What invention do you wish existed?",
        "If you had to teach a class on anything, what would it be?",
        "What would your alter ego be like?",
        "If you could wake up tomorrow with one new ability, what would it be?",
        "What would you create if you knew no one would judge it?",
        "If your life was a movie, what genre would it be?",
        "What legacy do you want to leave behind?",
        "If you could send a message to everyone on Earth, what would you say?",
        "What would you do differently if you started life over with all your current knowledge?",
        "If you could have any view from your window, what would it be?",
        "What's a tradition you'd like to start?",
        "If you could collaborate with anyone on a project, who would it be?",
        "What would your perfect morning routine look like?",
        "If you could live another person's life for a week, whose would you choose?",
        "What would you want to be remembered for?",
    ],

    fun: [
        "If you could have any superpower, what would you choose and why?",
        "What's your favorite childhood memory?",
        "What's the most embarrassing thing you believed as a kid?",
        "If you had to delete all but 3 apps from your phone, which would you keep?",
        "What's your most irrational fear?",
        "If you could be any age forever, what age would you choose?",
        "What's the weirdest compliment you've ever received?",
        "If you were a character in a show, what would your special ability be?",
        "What's something that always makes you laugh?",
        "If you could instantly become an expert in any hobby, what would it be?",
        "What's the worst fashion choice you've ever made?",
        "If animals could talk, which would be the rudest?",
        "What's a hill you're willing to die on that doesn't matter at all?",
        "What's the best meal you've ever had?",
        "If you could only eat one cuisine for the rest of your life, what would it be?",
        "What's a movie you can quote way too much of?",
        "What's your guilty pleasure song?",
        "If you had to wear one outfit for the rest of your life, what would it be?",
        "What's the most useless talent you have?",
        "What would your entrance music be?",
        "If you were a pizza topping, what would you be?",
        "What's the strangest thing you've ever eaten?",
        "What's your go-to karaoke song?",
        "If you could ban one minor inconvenience from existence, what would it be?",
        "What's the best random act of kindness you've witnessed?",
        "What show have you rewatched the most?",
        "If you had to survive a zombie apocalypse with one person you know, who would you pick?",
        "What's the most interesting thing you've learned recently?",
        "What's a word you love the sound of?",
        "If you could have an unlimited supply of one thing, what would it be?",
        "What's your unpopular food opinion?",
        "What would be the worst superpower to have?",
        "If you could make one rule everyone had to follow, what would it be?",
        "What's the best gift you've ever received?",
        "What's something you're terrible at but enjoy doing anyway?",
    ],

};